project:
  group: laplacian
  name: common-model
  type: domain-model
  namespace: laplacian.common
  version: '1.0.0'
  description:
    en: |
      Defines the generally applicable models that is not specific to a certain domain.
    ja: |
      特定のドメインに特化していない汎用的に適用できるモデルを定義します。
    zh: |
      定义了不特定于某一领域的普遍适用模型。
  source_repository:
    url: https://github.com/laplacian-core/common-model.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  model_files:
  - 'dest/model'
