project:
  sources:
  - "model/project/language_code_list.yaml"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/entities/localized_text.yaml"
  - "src/entities/multilingual_text.yaml"
  - "src/entities/named_param.yml"
  - "src/entities/named_value.yml"
  - "src/value_domain_types/language.yaml"
  - "template/src/entities/multilingual_text.yaml.hbs"
  - "template/src/value_domain_types/language.yaml.hbs"
